baseURL: "https://fredrix96.github.io/"
languageCode: "en-us"
title: "Fredrik Lind Portfolio"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "My Portfolio"
  description: A place where I showcase my resume, projects and more
  #staticPath: "static"  # The path to serve the static files from
  favicon: "/resources/portfolio.png"

  theme:
    disableThemeToggle: true
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  #color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #  darkmode:
  #     textColor:
  #     secondaryTextColor:
  #    backgroundColor: "#040204"
  #     secondaryBackgroundColor: "white"
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Fredrik"
    subtitle: "and this is my portfolio"
    content: "Recent Master of Science graduate in Game and Software Engineering. A strong problem solver, a meticulous code writer and a great teamplayer. My interests lie in games, technology and science."
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "https://www.canva.com/design/DAE3G6-3nL4/jilHindsDyvmISQGj1ZRhw/view?utm_content=DAE3G6-3nL4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/fredrix96
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/fredrik-lind-50616b5b/
        - icon: fab fa-soundcloud
          url: https://soundcloud.com/fflind
      customIcons:
        - icon: /resources/gamejolt.png
          url: "https://gamejolt.com/@FredrikLind/games"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/resources/me.png"
    content: |-
      I am a software engineer with a passion for game development. I have a background in computer science and mathematics, and I have a strong interest in technology and science.
      I am currently working on my own 2D game in Unity.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C++"
        - "C#"
        - "Unity"
        - "DirectX 12"
        - "OpenGL"
        - "WebGL"

  # Experience
  experience:
    enable: true
    items:
      - job: "Java Developer (Internship)"
        company: "Colmeo"
        companyUrl: "https://www.colmeo.se/"
        date: "Jan 2022 - Feb 2022"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://eyeatproduction.com"
        info:
          enable: true
          content: This job was remote
        content: "I got the opportunity to have a short internship at Colmeo (Eye at Production) where I helped them with their app \"FilmTheFault\" during the month of January. I worked with Java in Android Studio."
        image: "/resources/colmeo.png"

      - job: "Mailman"
        company: "PostNord"
        companyUrl: "https://www.postnord.se/en"
        date: "Jun 2015 - Aug 2020"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: Fulltime Jun 2015 - Jul 2016 Seasonal Jun 2017 - Aug 2020
        content: "I distributed and collected letters from several mailboxes, postal agents, and companies.
        I also helped with food delivery for a company called \"Linas Matkasse\" for a few weeks during the time when PostNord and Linas Matkasse had a collaboration."
        image: "/resources/postnord.png"
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Science in Game and Software Engineering"
        school:
          name: "Blekinge Institute of Technology, Karlskrona"
          url: "https://www.bth.se/eng/"
        date: "2016 - 2021"
        #GPA: "3.8 out of 5.0"
        content: |-
            - The program contained courses such as: Multivariable Calculus, Linear Algebra, C & C++, Databases (MySQL + Python), Game Physics, OpenGL, DirectX 12, WebGL, SCRUM and Git. 
            - The program also contained two 3D game projects, showcased in my projects, and a thesis showcased in my publications.
        featuredLink:
          enable: true
          name: "Degree Certificate"
          url: "https://drive.google.com/file/d/1JMSmJLNzs6JaIRVZTOrGsNGq8r6nPfq7/view?usp=sharing"
        featuredLink2:
          enable: true
          name: "Certificate of Registration"
          url: "https://drive.google.com/file/d/16tDwLRnK9WIObN2ue--aB6pc2C5itZte/view?usp=sharing"
        image: "/resources/bth.png"
      - title: "Science of Engineering"
        school:
          name: "Hulebäcksgymnasiet (High School), Mölnlycke"
          url: "https://hulebacksgymnasiet.harryda.se/"
        date: "2012 - 2015"
        #GPA: "3.9 out of 5.0"
        content: |-
          - This was a Master of Science preparatory program.
          - The program contained courses such as: Math 1c, 2c, 3c, 4 & 5, Physics 1 & 2, Technology 1 & 2, Biology 1, Chemistry 1 & 2, CAD 1 & 2, Music production 1 & 2 and English 7 (advanced english).
        image: "/resources/hule.png"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: You can reach me here!
    email: f.flind@hotmail.com
    btnName: f.flind@hotmail.com

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/fredrix96
      linkedin: https://www.linkedin.com/in/fredrik-lind-50616b5b/
      soundcloud: https://soundcloud.com/fflind
      gamejolt: https://gamejolt.com/@FredrikLind/games
