baseURL: "http://fredriklind.me"
languageCode: "en-us"
title: "Fredrik Lind"
theme: hugo-profile

Paginate: 3
disqusShortname: fredriklind
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Show all pages
      name: Pages
      weight: 2
    - identifier: dropdown1
      title: Home Page
      name: Home
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: Hell Loop Page
      name: Hell Loop
      url: /hellloop
      parent: dropdown
      weight: 2
    - identifier: dropdown3
      title: Daedalus' Maze Page
      name: Daedalus' Maze
      url: /daedalusmaze
      parent: dropdown
      weight: 3
    - identifier: dropdown4
      title: Smaller Projects Page
      name: Smaller Projects
      url: /smallprojects
      parent: dropdown
      weight: 4

params:
  title: "My Portfolio"
  description: A place where I showcase my resume, projects and more
  #staticPath: "static"  # The path to serve the static files from
  favicon: "/resources/mylogo.png"

  theme:
    disableThemeToggle: true
    defaultTheme: "dark"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  #color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #  darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor: "#040204"
  #     secondaryBackgroundColor: "white"
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/resources/mylogo.png" # Logo for the brand | default is the favicon variable
    brandName: "Home" # Brand name for the brand | default is the title variable

  #menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disablePublications: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Fredrik"
    subtitle: "and this is my portfolio"
    content: "Recent Master of Science graduate in Game and Software Engineering. A strong problem solver, a meticulous code writer and a great teamplayer. My interests lie in games, technology and science."
    image: /resources/code.gif
    button:
      enable: true
      name: "Resume"
      url: "/resources/documents/Resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/fredrix96
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/fredrik-lind-50616b5b/
        - icon: fab fa-soundcloud
          url: https://soundcloud.com/fflind
      customIcons:
        - icon: /resources/gamejolt.png
          url: "https://gamejolt.com/@FredrikLind/games"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/resources/me.png"
    content: |-
      I am a software engineer with a passion for game development. I have a background in computer science and mathematics, and I have a strong interest in technology and science.
      I am currently working on my own 2D game in Unity.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C++"
        - "C#"
        - "Unity"
        - "DirectX 12"
        - "OpenGL"
        - "WebGL"

  # Experience
  experience:
    enable: true
    items:
      - job: "Java Developer (Internship)"
        company: "Colmeo"
        companyUrl: "https://www.colmeo.se/"
        date: "Jan 2022 - Feb 2022"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://eyeatproduction.com"
        info:
          enable: true
          content: This job was remote
        content: "I got the opportunity to have a short internship at Colmeo (Eye at Production) where I helped them with their app \"FilmTheFault\" during the month of January. I worked with Java in Android Studio."
        image: "/resources/colmeo.png"

      - job: "Mailman"
        company: "PostNord"
        companyUrl: "https://www.postnord.se/en"
        date: "Jun 2015 - Aug 2020"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: Fulltime Jun 2015 - Jul 2016 Seasonal Jun 2017 - Aug 2020
        content: "I distributed and collected letters from several mailboxes, postal agents, and companies.
        I also helped with food delivery for a company called \"Linas Matkasse\" for a few weeks during the time when PostNord and Linas Matkasse had a collaboration."
        image: "/resources/postnord.png"
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Science in Game and Software Engineering"
        school:
          name: "Blekinge Institute of Technology, Karlskrona"
          url: "https://www.bth.se/eng/"
        date: "2016 - 2021"
        #GPA: "3.8 out of 5.0"
        content: |-
            - The program contained courses such as: Multivariable Calculus, Linear Algebra, C & C++, Databases (MySQL + Python), Game Physics, OpenGL, DirectX 12, WebGL, SCRUM and Git.
            - The program also contained two 3D game projects, showcased in my projects, and a thesis showcased in my publications.
        featuredLink:
          enable: true
          name: "Degree Certificate"
          url: "/resources/documents/Degree Certificate.pdf"
        featuredLink2:
          enable: true
          name: "Certificate of Registration"
          url: "/resources/documents/Certificate of Registration.pdf"
        image: "/resources/bth.png"
      - title: "Science of Engineering"
        school:
          name: "Hulebäcksgymnasiet (High School), Mölnlycke"
          url: "https://hulebacksgymnasiet.harryda.se/"
        date: "2012 - 2015"
        #GPA: "3.9 out of 5.0"
        content: |-
          - This was a Master of Science preparatory program.
          - The program contained courses such as: Mathematics 4 & 5, Physics 2, Engineering 2, Biology 1, Chemistry 2, CAD 2, Music production 2 and English 7 (advanced english).
        image: "/resources/hule.png"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Unity 2D Game
        content: Currently working on a 2D game in Unity. You place buildings and gather an army to fight the never ending flow of enemies. The game is purely created programmatically. The art and music are created by me.
        image: /resources/unity.png
        page: /myunitygame
        badges:
          - "Unity"
          - "C#"
          - "Game"
        links:
          - icon: fab fa-github
            url: https://github.com/fredrix96/MyUnity2DGame

      - title: Hell Loop
        content: A game made by me and ten other students at Blekinge Institute of Technology. It is built from the ground up with our own engine in DirectX 12.
        image: /resources/hellLoop.jpg
        page: /hellloop
        featured:
          name: Download
          link: https://gamejolt.com/games/Hell_Loop/578483
        badges:
          - "DirectX 12"
          - "C++"
          - "Game"
        links:
          - icon: fab fa-github
            url: https://github.com/jocke1995/StortSpelProjekt
          - icon: fab fa-youtube
            url: https://youtu.be/EPoPFmjj784

      - title: Daedalus' Maze
        content: The first game I made together with four other students at Blekinge Institute of Technology. It is built from the ground up with our own engine in OpenGL.
        image: /resources/daedalusMaze.jpg
        page: /daedalusmaze
        featured:
          name: Download
          link: https://gamejolt.com/games/daedalusmaze/404262
        badges:
          - "OpenGL"
          - "C++"
          - "Game"
        links:
          - icon: fab fa-github
            url: https://github.com/Whixx/Small-Game-Project
          - icon: fab fa-youtube
            url: https://youtu.be/rK4MIVfmG8w

  # Publications
  publications:
    enable: true
    items:
      - title: >
          Maximizing performance gain of Variable Rate Shading tier 2 while maintaining image quality: Using post processing effects to mask image degradation
        content: The aim of this thesis was to examine how close Variable Rate Shading tier 2 screen space shading can come to the performance gains of Variable Rate Shading tier 1 while trying to maintain an acceptable image quality with the help of commonly used post processing effects."
        url: http://urn.kb.se/resolve?urn=urn:nbn:se:bth-21868

  #Contact
  contact:
    enable: true
    content: You can reach me here!
    email: f.flind@hotmail.com
    btnName: f.flind@hotmail.com

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/fredrix96
      linkedin: https://www.linkedin.com/in/fredrik-lind-50616b5b/
      soundcloud: https://soundcloud.com/fflind
      gamejolt: https://gamejolt.com/@FredrikLind/games
